sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 284100
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: hodaka-java-ai
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
    password: '284100'
    database: 10
  wechat:
    appid: wxe7d582fabd06097f
    secret: 0fd8d27c26836d82c45d919b8f15a445